word = input("enter your word : ")



dictonary = {
    "water": "paani",
    "book": "kitab",
    "pen": "kalam",
    "air": "hawa",
    "fire": "aag",
    "sun": "suraj",
    "moon": "chaand",
    "star": "tara",
    "earth": "zameen",
    "sky": "aasmaan",
    "tree": "ped",
    "flower": "phool",
    "house": "ghar",
    "heart": "dil",
    "friend": "dost",
    "love": "pyaar",
    "time": "waqt",
    "night": "raat",
    "day": "din",
    "food": "khana",
    "tea": "chai",
    "rain": "baarish",
    "river": "nadi",
    "mountain": "pahad",
    "city": "sheher",
    "village": "gaon",
    "man": "aadmi",
    "woman": "aurat",
    "child": "baccha",
    "father": "pita",
    "mother": "maa",
    "brother": "bhai",
    "sister": "behen",
    "work": "kaam",
    "money": "paisa",
    "hand": "haath",
    "eye": "aankh",
    "head": "sir",
    "life": "jeevan",
    "death": "maut",
    "doctor": "doctor",
    "school": "school",
    "teacher": "shikshak",
    "knowledge": "gyaan",
    "world": "duniya",
    "today": "aaj",
    "tomorrow": "kal",
    "morning": "subah",
    "evening": "shaam",
    "year": "saal",
    "light": "roshni",
    "darkness": "andhera",
    "white": "safed",
    "black": "kala",
    "red": "laal",
    "blue": "neela",
    "green": "hara",
    "food": "khana",
    "milk": "doodh",
    "bread": "roti",
    "rice": "chawal",
    "fruit": "phal",
    "fish": "machli",
    "door": "darwaza",
    "window": "khidki",
    "table": "mez",
    "chair": "kursi",
    "car": "gaadi",
    "train": "railgaadi",
    "phone": "phone",
    "computer": "computer",
    "good": "accha",
    "bad": "bura",
    "big": "bada",
    "small": "chhota",
    "new": "naya",
    "old": "purana",
    "happy": "khush",
    "sad": "udaas",
    "easy": "aasaan",
    "difficult": "mushkil",
    "one": "ek",
    "two": "do",
    "ten": "das",
    "hundred": "sau",
    "help": "madad",
    "love": "pyaar",
    "sleep": "neend",
    "eat": "khana",
    "go": "jaana",
    "come": "aana",
    "god": "bhagwan",
    "king": "raja"
}




print(dictonary.get(word))
