set = set()

user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)
user = int(input("enter the number "))
set.add(user)

print(set)